// Copyright (c) Bluscream. Licensed under the GPL-3.0 License.
// See the LICENSE file in the repository root for full license text.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text.Json;
using Bluscream;
using ModelContextProtocol.Server;

namespace Bluscream.Modules.HTTPServer.Mcp;

/// <summary>
/// MCP tools exposed to AI agents, backed by the live VRCOSC engine.
///
/// Every method here runs in-process via <see cref="ReflectionUtils"/>, so there is
/// no config-file scraping and no restart needed for changes to take effect.
///
/// Tool names, descriptions, and JSON input schemas are generated by the MCP SDK
/// from these signatures and attributes — do not hand-write schemas.
/// </summary>
[McpServerToolType]
internal static class McpTools
{
    private static readonly JsonSerializerOptions Indented = new() { WriteIndented = true };

    private static string Json(object data) => JsonSerializer.Serialize(data, Indented);

    [McpServerTool(Name = "vrcosc_status")]
    [Description("Get the live VRCOSC engine state: app manager state, active profile, current avatar, and chatbox text.")]
    public static string Status()
    {
        var avatar = ReflectionUtils.GetCurrentAvatarInfo();
        return Json(new
        {
            appManagerState = ReflectionUtils.GetAppManagerState() ?? "unknown",
            activeProfileId = ReflectionUtils.GetCurrentProfileId(),
            avatarId = avatar?.Id,
            avatarName = avatar?.Name,
            chatBoxText = ReflectionUtils.GetChatBoxText(),
            moduleCount = ReflectionUtils.GetAllModulesInfo()?.Count ?? 0,
        });
    }

    [McpServerTool(Name = "vrcosc_get_modules")]
    [Description("List all loaded modules with their id, enabled flag, and running state.")]
    public static string GetModules(
        [Description("Only return enabled modules")] bool enabledOnly = false)
    {
        var modules = ReflectionUtils.GetAllModulesInfo();
        if (modules == null)
            return "Unable to read modules — is the VRCOSC engine started?";

        IEnumerable<object> result = modules;
        if (enabledOnly)
            result = modules.Where(m => ReflectionUtils.GetMemberValue<bool>(m, "enabled"));

        var list = result.ToList();
        return Json(new { count = list.Count, modules = list });
    }

    [McpServerTool(Name = "vrcosc_start_modules")]
    [Description("Start the VRCOSC modules (equivalent to the play button).")]
    public static string StartModules(
        [Description("Force start even if VRChat is not detected")] bool force = false)
    {
        var error = force ? ReflectionUtils.ForceAppManagerStart() : ReflectionUtils.StartModules();
        return error == null
            ? $"Modules started{(force ? " (forced)" : "")}."
            : $"Failed to start modules: {error}";
    }

    [McpServerTool(Name = "vrcosc_stop_modules")]
    [Description("Stop the VRCOSC modules (equivalent to the stop button).")]
    public static string StopModules() =>
        ReflectionUtils.StopModules() ? "Modules stopped." : "Failed to stop modules.";

    [McpServerTool(Name = "vrcosc_get_osc_parameters")]
    [Description("List all known OSC parameters with their current values and types.")]
    public static string GetOscParameters(
        [Description("Case-insensitive substring to filter parameter names by")] string? filter = null)
    {
        var parameters = ReflectionUtils.GetAllOscParameters();
        if (parameters == null)
            return "Unable to read OSC parameters — is the VRCOSC engine started?";

        var filtered = string.IsNullOrEmpty(filter)
            ? parameters
            : parameters.Where(p => p.Name.Contains(filter!, StringComparison.OrdinalIgnoreCase)).ToList();

        return Json(new
        {
            count = filtered.Count,
            parameters = filtered.Select(p => new { name = p.Name, value = p.Value, type = p.Type }),
        });
    }

    [McpServerTool(Name = "vrcosc_get_osc_parameter")]
    [Description("Get the current value of a single OSC parameter by exact name.")]
    public static string GetOscParameter(
        [Description("Parameter name, e.g. VRCOSC/Weather/Code")] string name)
    {
        var result = ReflectionUtils.GetOscParameter(name);
        return result == null
            ? $"Parameter '{name}' not found."
            : Json(new { name, value = result.Value.Value, type = result.Value.Type });
    }

    [McpServerTool(Name = "vrcosc_set_osc_parameter")]
    [Description("Set an OSC parameter. Takes effect immediately on the running avatar.")]
    public static string SetOscParameter(
        [Description("Parameter name")] string name,
        [Description("Value to set — bool, number, or string")] JsonElement value)
    {
        if (!TryUnwrap(value, out var clr))
            return "Unsupported value type — pass a bool, number, or string.";

        var (success, error) = ReflectionUtils.SendOscParameter(name, clr!);
        return success ? $"Set {name} = {clr}" : $"Failed to set {name}: {error}";
    }

    [McpServerTool(Name = "vrcosc_send_raw_osc")]
    [Description("Send a raw OSC message on an arbitrary address through VRCOSC's own OSC client.")]
    public static string SendRawOsc(
        [Description("OSC address, e.g. /avatar/parameters/Foo")] string address,
        [Description("Value to send — bool, number, or string")] JsonElement value)
    {
        if (!TryUnwrap(value, out var clr))
            return "Unsupported value type — pass a bool, number, or string.";

        return ReflectionUtils.SendRawOSC(address, clr!)
            ? $"Sent {address} = {clr}"
            : $"Failed to send OSC to {address}";
    }

    [McpServerTool(Name = "vrcosc_get_chatbox")]
    [Description("Get the text currently displayed in the VRChat chatbox.")]
    public static string GetChatBox() =>
        ReflectionUtils.GetChatBoxText() ?? "Unable to read chatbox — is the VRCOSC engine started?";

    [McpServerTool(Name = "vrcosc_send_chatbox")]
    [Description("Send a message to the VRChat chatbox immediately.")]
    public static string SendChatBox(
        [Description("Message text")] string text,
        [Description("Use the minimal chatbox background")] bool minimalBackground = false) =>
        ReflectionUtils.SendChatBox(text, minimalBackground)
            ? $"Sent to chatbox: {text}"
            : "Failed to send chatbox message.";

    [McpServerTool(Name = "vrcosc_get_avatar")]
    [Description("Get the id and name of the avatar currently worn.")]
    public static string GetAvatar()
    {
        var avatar = ReflectionUtils.GetCurrentAvatarInfo();
        return avatar == null
            ? "No avatar information available — is VRChat connected?"
            : Json(new { id = avatar.Value.Id, name = avatar.Value.Name });
    }

    [McpServerTool(Name = "vrcosc_persist")]
    [Description("Flush in-memory module state to disk, or reload it from disk.")]
    public static string Persist(
        [Description("Either 'flush' (write to disk) or 'load' (read from disk)")] string direction) =>
        direction switch
        {
            "flush" => ReflectionUtils.FlushToDisk() ? "Module state flushed to disk." : "Failed to flush state to disk.",
            "load" => ReflectionUtils.LoadFromDisk() ? "Module state reloaded from disk." : "Failed to load state from disk.",
            _ => "direction must be 'flush' or 'load'",
        };

    /// <summary>Unwrap a JSON value into the CLR type VRCOSC's OSC layer expects.</summary>
    private static bool TryUnwrap(JsonElement el, out object? value)
    {
        switch (el.ValueKind)
        {
            case JsonValueKind.True: value = true; return true;
            case JsonValueKind.False: value = false; return true;
            case JsonValueKind.String: value = el.GetString(); return true;
            case JsonValueKind.Number:
                // VRChat distinguishes int and float parameters, so keep integers integral.
                value = el.TryGetInt32(out var i) ? i : el.GetSingle();
                return true;
            default:
                value = null;
                return false;
        }
    }
}
